### ISSUE TITLE
Android DEX support

### ISSUE THREAD

**Issue by ray-pixar** [footloosejava/JavaGoto#1]
Hi. this is a great implementation of GOTO. Is there chance to have Android support ? I know there is AsmDex but it is limited.

**Comment by footloosejava** [comment]
>> Hi. this is a great implementation of GOTO
Thanks! 
>> Is there chance to have Android support ? I
Probably not. But I welcome all enhancements! I'm not even sure if it works with java 1.8 and integrates with Lambdas. And I don't suggest actually using it for anything. It is a bit of a joke, but had a legit role in some Fortran code conversions.
